### ISSUE TITLE
Initializing two workers causes a seg-fault

### ISSUE THREAD

**Issue by kdumontnu** [rscarson/rustyscript#228] opened 2024-10-17 02:09 UTC
**Describe the bug**

**To Reproduce**
Running the following script:
```
use rustyscript::{worker::DefaultWorker, Error, Module};

fn main() -> Result<(), Error> {
    let worker = DefaultWorker::new(Default::default())?;
    let worker2 = DefaultWorker::new(Default::default())?;

    let module = Module::new("test.js", "export function add(a, b) { return a + b; }");
    let module_id = worker.load_module(module)?;

    let result: i32 =
        worker.call_function(Some(module_id), "add".to_string(), vec![1.into(), 2.into()])?;
    println!("{}", result);
    Ok(())
}
```
Causes a seg fault. I ran into this issue when trying to run on multiple threads ([see here](https://github.com/rscarson/rustyscript/discussions/227))

**Desktop (please complete the following information):**
 - OS: Linux
 - rustyscript = "0.8.3"

**Additional context**

**Comment by utyfua** [comment] 2024-10-17 06:50
Did you try to call `rustyscript::utilities::init_platform`? https://github.com/rscarson/rustyscript/issues/213#issuecomment-2374115669

Also whenever you destroy created runtimes, you must be sure to drop them newest-to-oldest. #224

**Comment by rscarson** [comment] 2024-10-17 14:16
I am having trouble reproducing the crash on Windows or Linux

In your discussion post you mention the segfault happens on the 2nd call

It crashes on the first call for you in this sample?

**Comment by kdumontnu** [comment] 2024-10-17 18:21
It runs fine with `let worker2 = DefaultWorker::new(Default::default())?;` commented out, but seg-faults with it inline.

Is there any other context that would help to understand from my instance?

**Comment by rscarson** [comment] 2024-10-18 13:11
Interesting

Can you debug to find out exactly where it crashes?

**Comment by kovaszab** [comment] 2024-10-31 17:35
I suspect it could be solved by utilizing snapshots of the workers runtimes. I got similiar segfault error when tried to run 2 runtimes on separate threads. Debugging showed that internally the two runtimes used the same memory  map for their v8 engines, causing segfault. Fixed it via creating snapshots of the runtimes, which made them reference their own memory map not a global one. Might wortth a try in your usecase too.

**Comment by kdumontnu** [comment] 2024-10-31 17:39
> I suspect it could be solved by utilizing snapshots of the workers runtimes. I got similiar segfault error when tried to run 2 runtimes on separate threads. Debugging showed that internally the two runtimes used the same memory map for their v8 engines, causing segfault. Fixed it via creating snapshots of the runtimes, which made them reference their own memory map not a global one. Might wortth a try in your usecase too.

Thanks! Do you have a code snippet you can link to? Might be worth updating in rustyscript examples.

**Comment by kovaszab** [comment] 2024-11-01 13:12
You can have a look at 'create_snapshot.rs' example, basically in my case I created 2 separate runtimes, created snapshots (for each of them becase they used different extensions) and then loaded them in separate threads. I think in your case, I'd create a runtime, snapshot it, and then initialize 2 workers with copies of the runtime snapshots. I could provide you a minimal example when I'll have time, in case you get stuck

**Comment by rscarson** [comment] 2024-11-01 13:21
Just out of curiosity does it change anything if you call init_platform manually with a larger count for thread pool

**Comment by rscarson** [comment] 2024-11-09 23:25
Some debug logs showing the memory issue would also be useful

**Comment by kovaszab** [comment] 2024-11-12 07:01
I'll have a look at my projects git history and prepare a simple example where this issue can be reproduced

**Comment by kovaszab** [comment] 2024-11-14 18:10
Unfortunately I couldn't reproduce the issue either, even though checked out the exact revision of my repository where the issue arised consistently on my linux host. Cargo.lock showed no change in dependencies that could influence these results

**Comment by rscarson** [comment] 2024-11-16 14:07
> Unfortunately I couldn't reproduce the issue either, even though checked out the exact revision of my repository where the issue arised consistently on my linux host. Cargo.lock showed no change in dependencies that could influence these results

Going to close this for now then
Please reopen this issue if it happens again

**Closed** 2024-11-16 14:07 UTC

**Comment by vladkorotnev** [comment] 2025-09-12 12:58
Getting this too currently in a project — works just fine under MacOS but after moving it to a Linux VM in the cloud things started going bonkers.

Basically I keep around two different runtimes, one for quick tasks that is called frequently, and one for large tasks with many dependencies that gets spun up on demand. The first is created when the REST API is initialized, the latter is created when an API requiring a large task is called. So once I call that API, the new runtime causes a segfault. 

Not sure how to work around this either as in my case the runtimes are configured differently so snapshots wouldn't be a great solution. (Albeit probably a good idea performance-wise)

**Comment by utyfua** [comment] 2025-09-12 13:04
> Getting this too currently in a project — works just fine under MacOS but after moving it to a Linux VM in the cloud things started going bonkers.
> 
> Basically I keep around two different runtimes, one for quick tasks that is called frequently, and one for large tasks with many dependencies that gets spun up on demand. The first is created when the REST API is initialized, the latter is created when an API requiring a large task is called. So once I call that API, the new runtime causes a segfault.
> 
> Not sure how to work around this either as in my case the runtimes are configured differently so snapshots wouldn't be a great solution. (Albeit probably a good idea performance-wise)

Are you sure you are not accidentally create a third runtime?
Whenever you destroy created runtimes, you must be sure to drop them newest-to-oldest [[ref](https://github.com/rscarson/rustyscript/issues/224#issuecomment-2407738090)]

**Comment by vladkorotnev** [comment] 2025-09-12 13:11
Yes, absolutely.

Here is the workaround that helped me, hopefully useful for anyone else coming here from Google like myself:

```rust
    fn init_runtime(_options: Self::RuntimeOptions) -> Result<rustyscript::Runtime, Error> {
        // This is to work around a crash on Linux that somehow makes two runtimes in one process send things bonkers and do a segfault!
        let snapshot = Box::leak(rustyscript::SnapshotBuilder::new(Default::default())?
            .finish());

        let options = rustyscript::RuntimeOptions {
            startup_snapshot: Some(snapshot),
            ..Default::default()
        };
        rustyscript::Runtime::new(options)
    }
```

Note that this leaks the snapshot buffer so it's not suited for runtimes that get spun up and shut down, unless you can just reuse the same buffer? Or someone smarter than me might come up with a magic spell of lifetimes and do it cleaner.

For now I've put this in the long lived worker for the small tasks, so that there is just one permanently allocated snapshot in the program, and testing it now the large task runtime can be spun up on demand without any issue. If I added a third runtime I presume things would explode again, luckily, I don't need it :-)

**Comment by utyfua** [comment] 2025-09-12 13:18
If you build snapshot each time you create runtime then just DO NOT use it in a first place(keep default `None`).

**Comment by vladkorotnev** [comment] 2025-09-12 13:21
Well here's the trick — it crashes with the default. An empty snapshot however fixes it. So I make an empty snapshot in the long-lived runtime and use the default in the short-lived ones. 

Not a clean solution but good enough to wait until this is fixed upstream in Deno, as it seems to not be a Rustyscript problem from what I fathom so far.

**Comment by rscarson** [comment] 2025-09-12 13:56
> Yes, absolutely.
> 
> Here is the workaround that helped me, hopefully useful for anyone else coming here from Google like myself:
> 
> ```rust
>     fn init_runtime(_options: Self::RuntimeOptions) -> Result<rustyscript::Runtime, Error> {
>         // This is to work around a crash on Linux that somehow makes two runtimes in one process send things bonkers and do a segfault!
>         let snapshot = Box::leak(rustyscript::SnapshotBuilder::new(Default::default())?
>             .finish());
> 
>         let options = rustyscript::RuntimeOptions {
>             startup_snapshot: Some(snapshot),
>             ..Default::default()
>         };
>         rustyscript::Runtime::new(options)
>     }
> ```
> 
> Note that this leaks the snapshot buffer so it's not suited for runtimes that get spun up and shut down, unless you can just reuse the same buffer? Or someone smarter than me might come up with a magic spell of lifetimes and do it cleaner.
> 
> For now I've put this in the long lived worker for the small tasks, so that there is just one permanently allocated snapshot in the program, and testing it now the large task runtime can be spun up on demand without any issue. If I added a third runtime I presume things would explode again, luckily, I don't need it :-)

So the concept behind snapshots is just that they load faster because all of the JavaScript for the extensions has already been run the first time. The reason it's so difficult to make them live in your program and then use them is because there's really no benefit of doing that because creating the snapshot is orders of magnitude slower that just creating a runtime without a snapshot 

I would be surprised if it was the problem but if you are using snapshots like this do not use snapshots

**Comment by rscarson** [comment] 2025-09-12 14:07
Also the snapshot builder is in fact a runtime, and as such could definitely cause the crash if that and the main runtime were dropped in the wrong order :)
