### ISSUE TITLE
error[E0433]: failed to resolve: could not find `deno_core` in the list of imported crates

### ISSUE THREAD

**Issue by gc-victor** [rscarson/rustyscript#30] opened 2023-11-03 15:17 UTC
I'm having this error. Actually, it is weird because it is compiling the version 1.4 and I'm using the 1.3.

https://github.com/gc-victor/query/actions/runs/6746948992/job/18342101634#step:6:124

**Comment by rscarson** [comment] 2023-11-03 15:58
Compiling your crate now to try and find the issue

For the version, you need to specify '=0.1.2' to stick with that exact version

Also, consider adding Cargo.lock to the repo to cement the versions used

**Comment by rscarson** [comment] 2023-11-03 16:33
Related to a change in deno_core here: https://github.com/denoland/deno_core/commit/16970b70f3640cc0b3023eb342dcfbee93d1d112

Seems they altered op2 to require deno_core as a direct dependency for some reason?

You will need to add:
```
deno_core = "0.224.0"
```

in Cargo.toml for now until I can get this sorted on their end

**Comment by gc-victor** [comment] 2023-11-03 16:35
Good one! Thanks!

**Comment by rscarson** [comment] 2023-11-03 16:36
Going to leave this open so I can link it to an issue on deno_core, actually

**Comment by rscarson** [comment] 2023-11-10 21:33
Can you confirm your issue is gone in the current github version of the crate?

**Comment by gc-victor** [comment] 2023-11-10 22:32
Adding deno_core as a dependency the issue is gone

**Comment by rscarson** [comment] 2023-11-10 23:03
> Adding deno_core as a dependency the issue is gone

In the new version that won't be required anymore

**Comment by gc-victor** [comment] 2023-11-11 05:34
That's great! I will test it. Thanks!

**Comment by rscarson** [comment] 2023-11-11 13:54
Yeah I have not been able to publish the release yet due to an issue with the crate workspace configs

Fixing it this morning sorry

**Comment by rscarson** [comment] 2023-11-11 19:00
Fixed in 0.2.0

**Closed by rscarson** 2023-11-11 19:00 UTC

**Comment by gc-victor** [comment] 2023-11-13 08:22
I have this error with the version 0.2.0:

```
error[E0433]: failed to resolve: use of undeclared crate or module `deno_fetch`
deno_fetch::deno_fetch::init_ops_and_esm::<Permissions>(Default::default()),
   |         ^^^^^^^^^^ use of undeclared crate or module `deno_fetch`
```

**Comment by Rajdeep-TG** [comment] 2023-11-13 10:55
The issue is that the `web` feature previously had `deno_fetch` in it, and it should have it now as well, but it has been (probably accidentally) removed. `deno_fetch` is required for the `web` extension to work.

**Comment by rscarson** [comment] 2023-11-13 13:42
You are correct I'll put out an emergency patch this morning and add a test that will catch such issues in the future
